"""add rating updated timestamp

Revision ID: 284e8735068f
Revises: 24b6a1828dfd
Create Date: 2026-09-16 06:05:37.424672

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '284e8735068f'
down_revision: str | Sequence[str] | None = '24b6a1828dfd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('date_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'date_updated')
    # ### end Alembic commands ###
